// vue/src/components/signup.vue
<template lang="html">
  <form @submit.prevent="onSignup">
    <div class="form-group">
      <label for="name">Name</label>
      <input
        type="name"
        id="name"
        name="name"
        v-model="user.name"
        class="form-control" required>
    </div>
    <div class="form-group">
      <label for="email">Email</label>
      <input
        type="email"
        id="email"
        name="email"
        v-model="user.email"
        class="form-control" required>
    </div>
    <div class="form-group">
      <label for="password">Password</label>
      <input
        type="password"
        id="password"
        name="password"
        v-model="user.password"
        class="form-control" required>
    </div>
    <button type="submit" class="btn btn-primary">Sign in</button>
  </form>
</template>

<script>
  import axios from 'axios'
  export default {
    data () {
      return {
        user: {
          name: '',
          email: '',
          password: ''
        }
      }
    },
    methods: {
      onSignup () {
        axios.post('http://localhost:8000/api/user/signup',
          { name: this.user.name, email: this.user.email, password: this.user.password },
          {headers: new Headers({'X-Requested-With': 'XMLHttpRequest'})})
          .then((response) => console.log(response))
          .catch((error) => console.log(error))
      }
    }
  }
</script>

<style lang="css">
</style>

// angular/src/app/signup/signup.component.ts
import { Component, OnInit } from '@angular/core';
import { NgForm } from "@angular/forms"
import { AuthService } from "../../services/auth.service"

@Component({
  selector: 'app-signup',
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.css']
})
export class SignupComponent implements OnInit {

  constructor(private authService: AuthService) { }

  ngOnInit() {
  }

  onSignup(form: NgForm) {
    this.authService.signup(
      form.value.name, form.value.email, form.value.password)
      .subscribe(
        response => console.log(response),
        error => console.log(error)
      );
  }

}

<form (ngSubmit)="onSignup(f)" #f="ngForm">
  <div class="form-group">
    <label for="name">name</label>
    <input
      type="text"
      id="name"
      name="name"
      ngModel
      class="form-control" required>
  </div>
  <div class="form-group">
    <label for="email">Email</label>
    <input
      type="email"
      id="email"
      name="email"
      ngModel
      class="form-control" required>
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input
      type="password"
      id="password"
      name="password"
      ngModel
      class="form-control" required>
  </div>
  <button type="submit" [disabled]="!f.valid" class="btn btn-primary">Sign up</button>
</form>
