// vue/src/components/quotes.vue
<template>
  <div class="container">
    <button class="btn btn-primary" @click="onGetQuotes($event)">Get Quotes</button>
    <hr>
    <app-quote
      v-for="quote in quotes"
      :qt="quote"
      :key="quote.id"
      @quoteDeleted="onQuoteDeleted">
    </app-quote>
  </div>
</template>

<script>
import Quote from './quote.vue'
import axios from 'axios'
export default {
  data () {
    return {
      quotes: []
    }
  },
  methods: {
    onGetQuotes () {
      axios.get('http://localhost:8000/api/quote')
        .then(response => {
          this.quotes = response.data.quotes
        })
        .catch(err => console.log(err))
    },
    onQuoteDeleted (id) {
      const position = this.quotes.findIndex((element) => {
        return element.id === id
      })
      this.quotes.splice(position, 1)
    }
  },
  components: {
    'app-quote': Quote
  }
}
</script>

<style lang="css">
</style>

// angular/src/app/quotes/quotes.component.ts
import { Component, OnInit } from '@angular/core';
import { Quote } from '../quote.interface';
import { QuoteService } from '../../services/quote.service';

@Component({
  selector: 'app-quotes',
  templateUrl: './quotes.component.html',
  styleUrls: ['./quotes.component.css']
})
export class QuotesComponent implements OnInit {
  quotes: Quote[];

  constructor(private quoteService: QuoteService) { }

  ngOnInit() {
  }

  onGetQuotes() {
    this.quoteService.getQuotes().subscribe(
      (quotes: Quote[]) => this.quotes = quotes,
      (error: Response) => console.log("rumbar", error)
    );
  }

  onDeleted(quote:Quote) {
    const position = this.quotes.findIndex((quoteEl: Quote) => {
      return quoteEl.id == quote.id
    });
    this.quotes.splice(position, 1);
  }
}

<button class="btn btn-primary" (click)="onGetQuotes()">Get Quotes</button>
<app-quote *ngFor="let quote of quotes" [quote]="quote" (quoteDeleted)="onDeleted($event)"></app-quote>
