// vue/src/components/signin.vue
<template lang="html">
  <form @submit.prevent="onSignin">
    <div class="form-group">
      <label for="email">Email</label>
      <input
        type="email"
        id="email"
        name="email"
        v-model="user.email"
        class="form-control" required>
    </div>
    <div class="form-group">
      <label for="password">Password</label>
      <input
        type="password"
        id="password"
        name="password"
        v-model="user.password"
        class="form-control" required>
    </div>
    <button type="submit" class="btn btn-primary">Sign in</button>
  </form>
</template>

<script>
  import axios from 'axios'
  export default {
    data () {
      return {
        user: {
          email: '',
          password: ''
        }
      }
    },
    methods: {
      onSignin () {
        axios.post('http://localhost:8000/api/user/signin',
          { email: this.user.email, password: this.user.password },
          {headers: new Headers({'X-Requested-With': 'XMLHttpRequest'})})
          .then((response) => {
            localStorage.setItem('token', response.data.token)
          })
          .catch((error) => console.log(error))
      }
    }
  }
</script>

<style lang="css">
</style>

// angular/src/app/signin/signin.component.ts
import { Component, OnInit } from '@angular/core';
import { AuthService } from '../../services/auth.service'
import { NgForm } from '@angular/forms'

@Component({
  selector: 'app-signin',
  templateUrl: './signin.component.html',
  styleUrls: ['./signin.component.css']
})
export class SigninComponent implements OnInit {

  constructor(private authService: AuthService) { }

  ngOnInit() {
  }

  onSignin(form: NgForm) {
    this.authService.signin(form.value.email, form.value.password)
      .subscribe(
        tokenData => console.log(tokenData),
        error => console.log(error),
      );
  }

}

<form (ngSubmit)="onSignin(f)" #f="ngForm">
  <div class="form-group">
    <label for="email">Email</label>
    <input
      type="email"
      id="email"
      name="email"
      ngModel
      class="form-control" required>
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input
      type="password"
      id="password"
      name="password"
      ngModel
      class="form-control" required>
  </div>
  <button type="submit" [disabled]="!f.valid" class="btn btn-primary">Sign in</button>
</form>
